[package]
name = "rustwide"
version = "0.7.0"
authors = ["Pietro Albini <pietro@pietroalbini.org>"]
edition = "2018"
build = "build.rs"

documentation = "https://docs.rs/rustwide"
repository = "https://github.com/rust-lang/rustwide"
description = "Execute your code on the Rust ecosystem."
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = ["unstable"]

[features]
unstable = []

[dependencies]
failure = "0.1.3"
futures = "0.1.13"
log = "0.4.6"
tokio = "0.1.11"
tokio-process = "0.2.3"
nix = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
scopeguard = "1.0.0"
lazy_static = "1.0.0"
winapi = "0.3"
tempfile = "3.0.0"
reqwest = "0.9"
flate2 = "1"
tar = "0.4.0"
percent-encoding = "2.1.0"
walkdir = "2.2"
toml = "0.5"
fs2 = "0.4.3"
remove_dir_all = "0.5.2"
base64 = "0.10.1"
getrandom = { version = "0.1.12", features = ["std"] }

[dev-dependencies]
env_logger = "0.6.1"
tiny_http = "0.6.2"
